metadata:
  name: aceestfitness-blue
spec:
  selector:
    matchLabels:
      version: blue
  template:
    metadata:
      labels:
        app: aceestfitness
        version: blue
    spec:
      containers:
      - name: aceestfitness
        image: itzzmeakhi/aceestfitness:1.0.0
