spec:
  replicas: 5
  selector:
    matchLabels:
      app: aceestfitness
  template:
    metadata:
      labels:
        app: aceestfitness
        track: canary
    spec:
      containers:
      - name: aceestfitness
        image: itzzmeakhi/aceestfitness:1.2.0
