metadata:
  name: aceestfitness-green
spec:
  selector:
    matchLabels:
      version: green
  template:
    metadata:
      labels:
        app: aceestfitness
        version: green
    spec:
      containers:
      - name: aceestfitness
        image: itzzmeakhi/aceestfitness:1.1.0
